# Generated by Django 5.1.4 on 2024-12-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_postrevision_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
