# Generated by Django 5.1.4 on 2024-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_last_view_date_post_trending_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutus',
        ),
        migrations.AddField(
            model_name='post',
            name='cache_ttl',
            field=models.PositiveIntegerField(default=3600, help_text='Cache time-to-live in seconds'),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_structure_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image_optimization',
            field=models.JSONField(default=dict, help_text='Store image optimization metadata'),
        ),
        migrations.AddField(
            model_name='post',
            name='lazy_loading',
            field=models.BooleanField(default=True, help_text='Enable lazy loading for images'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_robots',
            field=models.CharField(default='index, follow', help_text='Robot meta tag instructions', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='og_type',
            field=models.CharField(default='article', help_text='Open Graph type', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='readability_score',
            field=models.FloatField(default=0, help_text='Flesch Reading Ease score'),
        ),
        migrations.AddField(
            model_name='post',
            name='secondary_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated secondary keywords', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_card_type',
            field=models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50),
        ),
    ]
